name: Build

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.18.0
            - uses: actions/setup-go@v2
              with:
                  go-version: ^1.20.0
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly
            - name: Install dependencies
              working-directory: ./web3
              run: npm install
            - name: Run Hardhat compile
              working-directory: ./web3
              run: npx hardhat compile
            - name: Install seer
              run: go install github.com/G7DAO/seer@latest
            - name: Build everything
              run: |
                  make